---
title: ' النسب في اللغة: يوم ---> يومي .... ساعة ---> ؟؟؟' 
author: Ayman Amin
date: '2019-09-14'
categories:
  - Arabic Language 
tags:
  - Arabic
summary: النسب في اللغة  
Arabic: Quran
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```




قد يُعرًف النسب في اللغة بشكل عام علي انه " إلحاق آخر الاسم ياء مشددة مكسور ما قبلها، للدلالة على نسبة شيء إلى آخر". 
وهنا يسمى الاسم المتصل بياء النسب "منسوباً"، ويسمى قبل اتصاله بها "منسوباً إليه"، وتسمى الياء المشددة "ياء النسب". 
مثلاً أقول ...يعمل فلان بأجر "يومي"...فهنا "يومي" منسوب إلي "يوم".

لكن يجب أن نلاحظ أن كثيراً ما يحدث في الإسم بعض التغييرات أثناء عملية النسب، ومن أهمها حذف تاء التأنيث من الإسم قبل إضافة ياء النسب.
فمثلاً أقول ...يعمل فلان بأجر "سنوي"... فهنا "سنوي" منسوب إلي "سنة"، والتغيير الذي حدث تم حذف تاء التأنيث وإرجاع الكلمة لاصلها وهو "سنو" ثم إضافة ياء النسب.

كثيراً ما نستخدم النسب في حياتنا اليومية لمقاييس الزمن، مثل يومي – اسبوعي – شهري-سنوي – وغيرهم.

قديماً لم يكن هناك حاجة للنسب لمقاييس زمنية أقل من يوم، لكن الآن مع تعقد الحياة والتقدم التكنولوجي جعلنا نقييس الاشياء في مقاييس زمنية قصيرة (ساعة – دقيقة – ثانية)، ونظراً لركاكة اللغة وضعفها عندنا أصبح ليس لدينا القدرة علي ايجاد النسب الصحيح لغوياً لهذه المقاييس. فمثلاً، لم اجد أحد يتكلم عن النسب لمقياس الزمن ساعة بالرغم من الحاجة اليه في كثير من امورنا اليومية.... الفني والمدرس وغيرهما الذي يعمل بالساعة، نقول يعمل بأجرة كل ساعة ولا نضع منسوباً الي "ساعة"، مثلها استهلاك المرافق نقول استهلاك الكهرباء كل ساعة، وغيرهما أمثلة كثيرة.

ما دفعني للكلام عن النسب في اللغة، أني حالياً مهتم في تخصصي بتحليل البيانات ذات الدورية العالية والتي تُجمع كل ساعة، من أهمها استهلاك المرافق، فوجدت كثير من الباحثين يقولون بيانات يومية شهرية سنوية، وعندما تكون الدورية "كل ساعة" يقولون بيانات كل ساعة ولا ينسبونها....هذا مؤشر علي ضعف اللغة عندنا كباحثين قبل العوام.
حتي لا أطيل،،، النسب الي "ساعة"، بعد حذف تاء التأنيث وإضافة ياء النسب فتصبح "ساعِي" وهي علي نفس وزن "مالِي"، فأقول بيان "ساعي" كما أقول "عام مالي" أو بيانات "ساعية" كما أقول "سنوات مالية".

ملاحظة، لست متخصصاً في اللغة ولكن الحاجة دفعتني للبحث.
